source: source

title: <%= projectName %>
description: <%= projectDescription %>
tagline: <%= projectTagline %>
keywords: [<%= projectKeywords %>]
baseurl: ""

url: <%= projectUrl %>
future: false
show_drafts: false
lsi: true
limit_posts: 0

author:
  name: <%= authorName %>

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [
  "node_modules",
  "gulp.js",
  "gulpfile.coffee",
  "package.json",
  "README.md",
  "Gemfile",
  "Gemfile.lock"
]

defaults:
  -
    scope:
      path: ""
    values:
      layout: default
